### ISSUE TITLE
Bug: Ghillie Suit bush color is wrong on desert map

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#76]
Ghillie Suit is the bush disguise perk.
If you use it on a desert map, the bush color will be wrong.

https://imgur.com/zkgx8cn.png

**Comment by NoahTheLegend** [comment]
fixed in recent hotfix

**Comment by mugg91** [comment]
Not fixed. 
https://imgur.com/XwSVM2h.png (From kaww 3.0 server)
